version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: concurrently
    versions:
    - 6.0.0
    - 6.0.1
