name: Tag creation

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get the version
        id: version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
        shell: bash

      - uses: ./
        id: semver
        with:
          version: ${{ steps.version.outputs.VERSION }}

      - name: Release
        if: ${{ steps.semver.outputs.version }}
        uses: softprops/action-gh-release@v1
        env:
          run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          # must use a separate token, not the built-in one to trigger subsequent builds
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          prerelease: ${{ !!steps.semver.outputs.prerelease }}
